shop/mainapp/urls.py
from django.urls import path, include
from .views import BaseView, ProductDetailView, CategoryDetailView, CartView, AddToCart

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCart.as_view(), name='add_to_cart')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/mainapp/models.py
import sys
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.urls import reverse
from PIL import Image

from io import BytesIO

User = get_user_model()


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


class MinResolutionErrorExeption(Exception):
    pass


class MaxResolutionErrorExeption(Exception):
    pass


class LatestProductsManages:
    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                                  reverse=True)
        return products


# LatestProducts.objects.get_products_for_main_page('notebook', 'smartphone', with_respect_to='notebook')

# from mainapp.models import LatestProducts

class LatestProducts:
    objects = LatestProductsManages()


class CategoryManager(models.Manager):
    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count',
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_category_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (4000, 4000)
    MAX_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание')
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        #
        # min_height, min_width = Product.MIN_RESOLUTION
        # max_height, max_width = Product.MIN_RESOLUTION
        #
        # if img.height < min_height or img.width < min_width:
        #     raise MinResolutionErrorExeption('Загруженное изображение слишком низкого разрешения')
        # if img.height > max_height or img.width > max_width:
        #     raise MaxResolutionErrorExeption('Загруженное изображение слишком большого размера')
        new_img = img.convert('RGB')
        resized_img = new_img.resize((800, 800))
        filestream = BytesIO()
        resized_img.save(filestream, 'JPEG', quality=90)
        filestream.seek(0)
        name = f'{self.image.name.split(".")}'
        self.image = InMemoryUploadedFile(filestream, 'ImageField', name, 'jpeg/image', sys.getsizeof(filestream), None)
        return super().save(*args, **kwargs)


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return f"Продук: {self.content_object.title}"

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', null=True, verbose_name='Покупатель', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_product = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адресс', null=True, blank=True)

    def __str__(self):
        return f'Покупатель: {self.user.first_name} {self.user.last_name}'


class Notebook(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Диагональ экрана')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=255, verbose_name="Частота процессора")
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    video = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время автономной работы')

    def __str__(self):
        return f'{self.category.name}: {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Диагональ экрана')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение эрана')
    accum_value = models.CharField(max_length=255, verbose_name='Объем батареи')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name="Наличие SD карты")
    sd_volume_max = models.CharField(max_length=255, null=True, blank=True,
                                     verbose_name='Максимальный объем встраимаевой памяти')
    main_cam_mp = models.CharField(max_length=255, verbose_name='Камера')
    frontal_cam_mp = models.CharField(max_length=255, verbose_name='Фронтальная камера')

    def __str__(self):
        return f'{self.category.name}: {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    # @property
    # def sd(self):
    #     if self.sd:
    #         return 'Да'
    #     return 'Нет'

shop/mainapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView, View
from django.http import HttpResponseRedirect
from django.contrib.contenttypes.models import ContentType
from .models import Notebook, Smartphone, Category, LatestProducts, Customer, Cart, CartProduct
from .mixins import CategoryDetailMixin, CartMixin


# Create your views here.
# def test_view(request):
#     categories = Category.objects.get_category_for_left_sidebar()
#     return render(request, 'base.html', {'categories': categories})


class BaseView(CartMixin, View):
    def get(self, request, *args, **kwargs):

        categories = Category.objects.get_category_for_left_sidebar()
        products = LatestProducts.objects.get_products_for_main_page('notebook', 'smartphone',
                                                                     with_respect_to='notebook')
        context = {
            'categories': categories,
            'products': products,
            'cart': self.cart
        }
        return render(request, 'base.html', context)


class ProductDetailView(CartMixin, CategoryDetailMixin, DetailView):
    CT_MODEL_CLASS = {
        'notebook': Notebook,
        'smartphone': Smartphone
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_CLASS[kwargs.get('ct_model')]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    # model = Model()
    # queryset = Model.objects.all()
    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ct_model'] = self.model._meta.model_name
        # context['cart'] = self.cart
        return context


class CategoryDetailView(CartMixin, CategoryDetailMixin, DetailView):
    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'
    #
    # def get(self, request, *args, **kwargs):
    #     categories = Category.objects.get_category_for_left_sidebar()
    #     products = LatestProducts.objects.get_products_for_main_page('notebook')
    #     context = {
    #         'categories': categories,
    #         'products': products
    #     }
    #     return render(request, 'base.html', context)


class AddToCart(CartMixin,  View):
    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product, created = CartProduct.objects.get_or_create(user=self.cart.owner, cart=self.cart, content_type=content_type,
                                                                  object_id=product.id
                                                                  )
        if created:
            self.cart.products.add(cart_product)
        return HttpResponseRedirect('/cart/')


class CartView(CartMixin, View):
    def get(self, request, *args, **kwargs):

        categories = Category.objects.get_category_for_left_sidebar()
        context = {
            'cart': self.cart,
            'categories': categories
        }

        return render(request, 'cart.html', context)

shop/mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'white')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'lightgray')
        }
    })
})(django.jQuery);
</script>
{% endblock %}

shop/mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="css/styles.css" rel="stylesheet"/>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                </li>

            </ul>
            <form class="d-flex">
                <a href="{% url 'cart' %}" class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Корзина
                    <span class="badge bg-dark text-white ms-1 rounded-pill">{{cart.products.count}}</span>
                </a>
            </form>
        </div>
    </div>
</nav>

<div class="container">

    <div class="row">

        <div class="col-lg-3 mt-5">
            <div class="list-group">
                {% for category in categories %}
                <a href="{{category.url}}" class="list-group-item">{{ category.name }} ({{ category.count }})</a>
                {% endfor %}
            </div>

        </div>
        <div class="col-lg-9">
            {% block content %}

            <section class="py-5">
                <div class="container px-4 px-lg-5 mt-5">
                    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                        {% for product in products %}

                        <div class="col mb-5">
                            <div class="card h-100">
                                <!-- Product image-->
                                <img class="card-img-top" src="{{product.image.url}}"
                                     alt="..."/>
                                <!-- Product details-->
                                <div class="card-body p-4">
                                    <div class="text-center">
                                        <!-- Product name-->
                                        <h5 class="fw-bolder">{{product.title}}</h5>
                                        <!-- Product price-->
                                        {{product.price}} руб.
                                    </div>
                                </div>
                                <!-- Product actions-->
                                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                    <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                                href="{{product.get_absolute_url}}">Подробнее</a></div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </section>
            {% endblock content %}
        </div>
    </div>
</div>


<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

shop/mainapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %} пуста {% endif %} </h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование товара</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Количество</th>
              <th scope="col">Общая цена</th>

    </tr>
  </thead>
  <tbody>
  {% for item in cart.products.all %}
    <tr>
      <th scope="row">{{ item.content_object.title }}</th>
      <td class="w-25"><img class="img-fluid" src="{{item.content_object.image.url}}" alt=""></td>
      <td>{{ item.content_object.price }}</td>
      <td>{{ item.qty }}</td>
              <td>{{ item.final_price }}</td>

    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock content %}

shop/mainapp/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item">{{category.name}}</li>
  </ol>
</nav>

<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for product in category_products %}

        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{product.image.url}}"
                     alt="..."/>
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{product.title}}</h5>
                        <!-- Product price-->
                        {{product.price}} руб.
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                href="{{product.get_absolute_url}}">Подробнее</a></div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock content %}

shop/mainapp/templates/notebook_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Диагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплея</td>
        <td>{{ product.display }}</td>
    </tr>
    <tr>
        <td>Частота процессора</td>
        <td>{{ product.processor_freq }}</td>
    </tr>
    <tr>
        <td>Оперативная память</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Видеокарта</td>
        <td>{{ product.video }}</td>
    </tr>
    <tr>
        <td>Время автономной работы</td>
        <td>{{ product.time_without_charge }}</td>
    </tr>
    </tbody>
</table>

shop/mainapp/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}
{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="#">{{product.category.name}}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
    </ol>
</nav>
<div class="row">

    <div class="col-md-4">
        <img src="{{product.image.url}}" alt="product.title" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{product.price}} руб.</p>
        <p>Описание: {{product.description}} руб.</p>
        <hr>
        <a href="{% url 'add_to_cart' ct_model=ct_model slug=product.slug %}"><button class="btn-danger">Добавить в корзину</button></a>
    </div>
    <p class="mt-4">Характеристики:</p>

    {{ product|product_spec }}

    <!--    {% if product.category.slug == 'notebooks' %}-->
    <!--        {% include 'notebook_specification.html' %}-->
    <!--    {% else %}-->
    <!--            {% include 'smartphone_specification.html' %}-->
    <!--    {% endif %}-->
</div>

{% endblock content %}

shop/mainapp/templates/smartphone_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Диагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплея</td>
        <td>{{ product.display }}</td>
    </tr>
    <tr>
        <td>Разрешение эрана</td>
        <td>{{ product.resolution }}</td>
    </tr>
    <tr>
        <td>Объем батареи</td>
        <td>{{ product.accum_value }}</td>
    </tr>
    <tr>
        <td>Оперативная память</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Слот карты памяти</td>
        <td>{{ product.sd }}</td>
    </tr>
    <tr>
        <td>Максимальный объем встраимаевой памяти</td>
        <td>{{ product.sd_volume_max }}</td>
    </tr>
    <tr>
        <td>Камера</td>
        <td>{{ product.main_cam_mp }}</td>
    </tr>
    <tr>
        <td>Фронтальная камера</td>
        <td>{{ product.frontal_cam_mp }}</td>
    </tr>
    </tbody>
</table>